### ISSUE TITLE
ignore secrets file if flag not present

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/pyglidein#136]
This error is annoying:
`Error Accessing Secrets File: .pyglidein_secrets.  Did you set the --secrets flag?`
Just assume no secrets if the flag is not specified.

**Comment by dsschult** [comment]
For those who think this is not urgent, two users and myself have all run into this.

**Comment by gonzalomerino** [comment]
The workaround for now is to "touch" an empty secrets file and point to it, correct?

**Comment by hskarlupka** [comment]
I understand this is annoying @dsschult.  The reason I did this was to make a point that pyGlidein requires a secrets file for storing sensitive data.  Since configs are commonly committed to the pyGlidein git repo there is a good chance that someone adds their AWS S3 Logging Credentials to the general configs if they didn't realize there was a special secrets file.  @gonzalomerino is right, the workaround here is to just touch an empty secrets file.
